### ISSUE TITLE
Atomic css loader

### ISSUE THREAD

**Issue by tom76kimo** [acss-io/atomizer#239]
Hi, I wrote a atomic css webpack loader called [atomic-loader] (https://github.com/tom76kimo/atomic-loader). It can parse atomic css classes when requiring modules and output the translated css. I am wondering if you can review it and give advices will be helpful :smile: . Thanks!

**Comment by renatoi** [comment]
Hey @tom76kimo, it looks really good. Thanks for doing it, someone already asked for it on a separate issue and you did it :) Thanks!

**Comment by tom76kimo** [comment]
My pleasure :)

**Comment by mdrohmann** [comment]
I actually made your atomic-loader into a [plugin](https://github.com/mdrohmann/atomic-plugin).  This way, the generated atomic.css file becomes a real webpack asset, which makes more sense to me. I just wanted to add this here...  Thank you, for your initial work tom76kimo.

**Comment by tom76kimo** [comment]
@mdrohmann  thanks :+1:

**Comment by src-code** [comment]
@tom76kimo @mdrohmann :+1: :+1: :+1: Really glad to see these, thanks for creating them!  Might have to include links to them in our docs site soon!

**Comment by tom76kimo** [comment]
Great! :+1:

**Comment by thierryk** [comment]
@tom76kimo @mdrohmann :+1: Thanks!

**Comment by soluml** [comment]
Great work @tom76kimo! We're using it on a new web product and it's performing wonderfully.

**Comment by tom76kimo** [comment]
It's really nice to hear that! Thanks!

**Comment by pankajparashar** [comment]
This is now part of the Atomic CSS organisation, and can be found here, https://github.com/acss-io/webpack-atomizer-loader

Thanks to @tom76kimo!
