### ISSUE TITLE
IE crashes child rows

### ISSUE THREAD

**Issue by mehowp** [acss-io/atomizer#266]
Hello. I've found bug, where IE does not calculate rows properely and makes them under each other. The reason is:
`@include column(calc((100% - #{(4*$_baseSize)} * #{($gridColumnsNumber/$i - 1)}) * #{($i / $gridColumnsNumber)}));`
instead of
`@include column(calc((100% - #{(4*$_baseSize)} * #{($gridColumnsNumber/$i - 1)}) * #{($i / $gridColumnsNumber) - 0.001}));`

**Comment by pankajparashar** [comment]
Are you sure this is a bug related to Atomizer? 

If yes then would you mind explaining how you're using Atomizer that resulted into this bug? Would be more than happy to help :-)

**Comment by mehowp** [comment]
Yep I'm sure. I dont know what does it happen but i think IE has different math in calc() function than webkit/firefox.
Example:
4 columns in row called c6 is like
` "calc((100% - 20px * 1) * 0.5)"`
And it makes them not opposite but every column is underneath. This happens only with IE so i was thinkin it may be caused of wrong property for "display" but when i did something like that:
`calc((100% - 20px * 1) * 0.499)`
It is working again :)

**Comment by src-code** [comment]
@mehowp It sounds like you're just running into a box model issue causing your layout to overflow.  The example you provided isn't Atomic CSS, so this isn't an Atomizer issue.  

FWIW, with Atomizer and Atomic CSS you'd put `calc()` in a custom value for a style such as `width`, eg:

```
<div class="W(mycalc)" />
```

Then you'd define "mycalc" as a custom value in your Atomizer config:

```json
{
    "custom": {
        "mycalc": "calc((100% - 20px * 1) * 0.499)" 
    }
}
```

Atomizer then generates the CSS for you:

```css
.W\(mycalc\) {
  width: calc((100% - 20px * 1) * 0.5);
}
```

That's really all Atomizer does - it's not running on the browser. So at this point if something isn't working, it's a browser issue.  

Also note that `calc()` is experimental and is not fully supported by IE:

https://developer.mozilla.org/en-US/docs/Web/CSS/calc
