### ISSUE TITLE
`Translate(Number, Number)` doesn't work

### ISSUE THREAD

**Issue by soluml** [acss-io/atomizer#271]
As the title says, using a class name like `Translate(-50%, -50%)` doesn't work.  `Translate(-50%)` spits out `transform: translate(-50%);` as expected.

**Comment by soluml** [comment]
`Translate(-50%,-50%)` does work. The space between the comma and last value seemingly prevents Atomizer from recognizing the value.

**Comment by src-code** [comment]
@soluml That's right, you can't have a space in there - not just because of Atomizer, but because a space is the boundary between two distinct classes, as far as the browser is concerned. So it's a non-starter as far as Atomizer is concerned.

**Comment by soluml** [comment]
True! The fact that I'm not only authoring Atomizer classes but browser classes as well may have slipped my mind 👍
