### ISSUE TITLE
Question: Referencing css class name

### ISSUE THREAD

**Issue by sarbbottam** [acss-io/atomizer#275]
This is more from HTML in JS perspective, to be precise, from react's perspective.

I could do like so:
```js
const Box = (props) => {
  const boxClass = 'W(100px) Lh(100px) Fz(30px) Ta(c) Bgc(#0280ae.5)';
  return (
    <div className={boxClass}>{props.text}</div>
  )
}

const Layout = () => {
  return (
    <div className="D(f) Jc(sb)">
      {
        [1,2,3,4].map(index => {
          return <Box text={`Box ${index}`}/>
        })  
      }
    </div>
  )
}
```

instead of using `W(100px) Lh(100px) Fz(30px) Ta(c) Bgc(#0280ae.5)` for className, I am referencing it from a variable.

```js
const Layout = () => {
  return (
    <div className="D(f) Jc(sb)">
      <div className="W(100px) Lh(100px) Fz(30px) Ta(c) Bgc(#0280ae.5)">Box 1</div>
      <div className="W(100px) Lh(100px) Fz(30px) Ta(c) Bgc(#0280ae.5)">Box 2</div>
      <div className="W(100px) Lh(100px) Fz(30px) Ta(c) Bgc(#0280ae.5)">Box 3</div>
      <div className="W(100px) Lh(100px) Fz(30px) Ta(c) Bgc(#0280ae.5)">Box 3</div>
    </div>
  )
}
```
Please see [this pen](http://codepen.io/sarbbottam/pen/dpmpxX).

However I could not get `Atomizer` to generate the dynamic classes.

**Am I doing something wrong?**

Thanks!

**Comment by pankajparashar** [comment]
@sarbbottam Would you mind running your first example on https://pankajparashar.com/atomizer-web?

As far as I checked, it works fine for me over there. If it works fine in the web app then there is no reason why it wouldn't work in the normal setup.

**Comment by sarbbottam** [comment]
@pankajparashar it works as desired on https://pankajparashar.com/atomizer-web. I could not get it to work with https://github.com/acss-io/atomizer-examples. May be I need to tweak the Gruntfile.

**Comment by pankajparashar** [comment]
I just tried the grunt example with the default setup and it worked as expected for me. It works fine in the editor plugins as well. Maybe you need to strip down your gruntfile to isolate the problem.

As far as the core library is concerned, I see no problem with that.

**Comment by sarbbottam** [comment]
Thanks @pankajparashar, let me try it again and update the thread.

**Comment by src-code** [comment]
Atomizer simply parses string content looking for valid Atomic classes, so it doesn't matter how your code is structured, or what language your code is written in (or if it's even code, for that matter.)  Sounds like this is more of an issue with how the tool is being run (grunt, command line, etc) than anything.

**Comment by sarbbottam** [comment]
Thanks @src-code probably I am doing something wrong.
