### ISSUE TITLE
What's wrong with breakpoints order?

### ISSUE THREAD

**Issue by againstall** [acss-io/atomizer#284]
Config:
```
"breakPoints": {
	    'xs': '@media screen and (min-width:0)', 
	    'sm': '@media screen and (min-width:576px)',
	    'msm': '@media screen and (max-width:575px)',
	    'mmd': '@media screen and (max-width:767px)', 
	    'md': '@media screen and (min-width:768px)',
            'lg': '@media screen and (min-width:992px)',
	    'mlg': '@media screen and (max-width:991px)',
	    'xl': '@media screen and (min-width:1200px)', 
	    'mxl': '@media screen and (max-width:1199px)' 
	},
```

Result:
![image](https://cloud.githubusercontent.com/assets/5334422/22998373/71801cec-f3e7-11e6-963b-573ebad9d264.png)

md breakpoint compiled below lg in the code and override rule

**Comment by tom76kimo** [comment]
It looks okay on the playground:
https://runkit.com/58a8518e86c06300158e23aa/58a8518e86c06300158e23ab

**Comment by againstall** [comment]
it was lg size, but because md rules compiled below in the code, rules was override :( I tried to change order rules, but same result

**Comment by tom76kimo** [comment]
I tried by using Chrome. Though the order of generated class is like below. ![](https://i.gyazo.com/b2f208803d0c599ed80beccc095928e9.png)

Yet the order will be correct in browser inspector. ![](https://i.gyazo.com/ad856cc6b310568df1be6380790356cf.png)

**Comment by src-code** [comment]
PR #286 should help here by giving you more control over source order of media queries.  We'll release this in v3.3.13

**Comment by src-code** [comment]
Closing since 3.4.0 was released - please reopen and add additional details if you're still having issues.
