### ISSUE TITLE
with 3.4.0 , seeing the TypeError: Cannot read property 'breakPoints' of undefined

### ISSUE THREAD

**Issue by chsanthosh** [acss-io/atomizer#289]
https://github.com/acss-io/atomizer/pull/286/files#diff-7536300d258a713b269818a5fb1fa74dR538

**Comment by src-code** [comment]
@chsanthosh Can you provide more details on how you were using Atomizer when you saw this error?  Eg, config file, etc.  A test case would be really helpful!

**Comment by src-code** [comment]
This was caused by calling the JSS API `jssToCss()` directly, not from Atomizer.  In that case, if `options.breakPoints` wasn't defined, this error would be thrown.  Atomizer always passes this object to the API, thus it only affects direct API access.
