### ISSUE TITLE
box-shadow not working

### ISSUE THREAD

**Issue by jitendravyas** [acss-io/atomizer#305]
```
<div class="Bxsh(0 2px 11px #000)">
    Some text
</div>
```

**Comment by thierryk** [comment]
@jitendravyas we cannot have spaces in Atomic classes or in any classes for that matter since they are "delimiters" (`Bxsh(0`, `2px`, `11px`, `#000)`). You'd need to use the config file to use such values; for example:

```js
"custom": {
  "1": "1px solid #000",
  "foo": "0 2px 11px #000"
}
```

---

```html
<div class="Bxsh(foo)">
    Some text
</div>
```
