### ISSUE TITLE
Fix inconsistency in "flex" classes

### ISSUE THREAD

**Issue by thierryk** [acss-io/atomizer#308]
Properties related to "flex" are not based on the same abbreviation. We have classes like `Flx`, `Flxg`, `Flxs`, and `Flxb` where "flex" has been abbreviated as "**Flx**"; and then classes like `Fld`, `Flf`, and `Flw` where "flex" has been abbreviated as "**Fl**".

"Unfortunately", none of these abbreviations match the [emmet](https://emmet.io) syntax which is "fx" (note that Emmet didn't have classes for `flex` at the time we came up with those names for ACSS).

I think we have 3 options:

   * Use the Emmet syntax for all cases above (replacing "Flx" and "Fl" with **Fx**)
   * Choose to go with **Flx** for all classes
   * Choose to go with **Fl** for all those classes

I don't like number 3 much and I think I prefer "Flx" to "Fx", but then we'd make an exception to our general rule of following what Emmet does. @src-code @renatoi, what do you guys think?
 
Of course we'd need to still support whatever syntax we abandon, making sure we mark those classes as deprecated.

**Comment by renatoi** [comment]
I vote for **adding** support for *Fx* to all classes but keeping the old ones so it is backwards compatible, but mark them as (deprecated), possibly removing them later on Atomizer 4 (not really a milestone in any roadmap) so it should be there for a while. The deprecation should serve 2 purposes:

1. Warn users to replace old instances to the new ones.
2. Remove them in the reference page.

**Comment by VinSpee** [comment]
I don't have a particularly strong opinion on which option, but my gut tells me that following @renatoi's plan makes the most sense while causing the least harm.
