### ISSUE TITLE
Allowing to pass multiple values inside "parenthesis" ?

### ISSUE THREAD

**Issue by thierryk** [acss-io/atomizer#309]
@renatoi @src-code 

Because we cannot have space inside classes we cannot do something like this:

```html
<div class="P(10px 5px)">content</div>
```

Authors would need to go "longhand":

```html
<div class="Py(10px) Px(5px)">content</div>
```

But what do you guys think of this (or something similar):

```html
<div class="P(10px,5px)">content</div>
```

Using **commas** (or something else) in lieu of spaces so devs can pass multiple values at once&mdash;without the need to rely on the config for that. 

We may have discussed this in the past but I don't remember what conclusion we reached... :-(

**Comment by jitendravyas** [comment]
This will be helpful for box shadows

**Comment by renatoi** [comment]
@jitendravyas This is a valid `box-shadow` declaration: `box-shadow: 3px 3px red, -1em 0 0.4em olive;`. How would you envision an atomic class that supports this declaration? I believe the conclusion we reached was that using custom names or creating a custom css class itself would be way easier. Remember that atomic css is not supposed to be the sole way to do CSS. If there's a better way to do it, then do it.

I like to think of creating websites/apps this way:

1 .atomic.css
2. custom-classes.css

Use 1 as much as you can, switch to 2 when you feel it would be just crazy to do it in ACSS.

For @thierryk case, padding might be a valid case, we could do it, but if I remember correctly, we thought about: `Py(10px) Px(5px)` being more reusable (and personally I think it's more declarative, meaning, I understand better) than `P(10px,5px)`. If you think this is really not that important or not a valid case we could implement it.

**Comment by idmytro** [comment]
I believe I can make PR for this.
For what properties do we need to do longhand?

Paddings, margins, border-colors, border-styles, border-widths...

**Comment by thierryk** [comment]
We did discuss the value of shorthand versus longhand and agreed that using the former was better from a performance/optimization perspective (class re-use).

I do think there is value in allowing authors to go longhand though as there may be cases where devs or teams cannot really edit the config at will.

But as @renatoi suggested, we should consider whitespace but commas too. Maybe this syntax could work?

```html
Bxsh(3px_3px_red,-1em_0_0.4em_olive)
```

But note that @src-code did something for `Bgp()` already, allowing multiple values (#230) to be passed;  **using `,` as the delimiter** (for space).

**Comment by idmytro** [comment]
Padding(margin, etc) shorthands are easy to understand and easy to write.
I prefer longhands by default, but imho it is nice to have a possibility to go shorthand if devs want to.

Alternative ways to use shorthands are:
1. Use variable `$p: "10px 5px"`, `P($p)`
2. Use custom rule `MyPaddings(10px,5px)`

Built-in possibility is much better than workarounds.

**Comment by jitendravyas** [comment]
@idmytro I wish to reduce dependency on AtomicConfig file.

**Comment by idmytro** [comment]
For box-shadows this "crazy" syntax can work 
`Bxsh(3px,3px,red,comma,-1em,0,0.4em,olive)` or even `Bxsh(3px,3px,red,|,-1em,0,0.4em,olive)`

**Comment by thierryk** [comment]
`Bgp()` now allows the passing of multiple parameters via comma but I don't really like that as it departs from ACSS efforts to use the same characters as in "plain CSS". What I mean by that is that we use `%` for percentage, `-` for minus, `.` for decimal point, `>` for child selector, `+` for adjacent selector,  and `_` for descendant selector (as `_` is "**usually/commonly**" used for *space*). Using `,` makes sense in term of *passing parameters*, but it does not reflect how it's done in plain CSS.

In my opinion, we should be using `,` for multiple values&mdash;which is **different** than multiple parameters&mdash;keeping with what we've been trying to achieve since day one; for example: 

```html
Bgi(image1,image2)
Bxsh(foo,bar)
```

I totally missed #230, I should have raised the issue then :-(

**Comment by xialvjun** [comment]
So, custom box-shadow is impossible?  I tried `Bxsh(3px,3px,red) Bxsh(0,0,3px,3px,red) Bxsh(0,0,3px,3px,#f00) Bxsh(3px,3px,#f00) Bxsh(#f00,3px,3px)` and replaced the value comma to space, neither works in https://pankajparashar-zz.github.io/atomizer-web/ ...

**Comment by thierryk** [comment]
> neither works in https://pankajparashar-zz.github.io/atomizer-web/ ...

Hi @xialvjun,

Please note that @pankajparashar-zz's tool uses Atomizer **v3.2.1**:

```
/**
 * Generated using Atomizer build v3.2.1. 
 * Copyright (c) 2015, Yahoo Inc. All rights reserved. **/
```

But the **latest** Atomizer release is **3.9.1**

**Comment by xialvjun** [comment]
@thierryk But I installed `atomizer@3.9.1` in my machine and test it, it still recognize none of those too.

**Comment by thierryk** [comment]
Sorry @xialvjun, I read the comment above ("for box-shadows this 'crazy' syntax can work") from @idmytro and assume that there had been a PR for this, but I've checked the releases and it's not the case.

Anyway, in my opinion, the best approach for this would be to use the config file as it'd allow you to use any value you want, even complex ones as suggested by @renatoi. 

On https://pankajparashar-zz.github.io/atomizer-web/ edit the config file (click on :gear:) so it looks like this: 

```
{
    "breakPoints": {
        "sm": "@media(min-width:750px)",
        "md": "@media(min-width:1000px)",
        "lg": "@media(min-width:1200px)"
    },
    "custom": {
        "1": "1px solid #000",
        "foo": "2px dotted #f00",
        "custom-shadow": "3px 3px red, -1em 0 0.4em olive"
    },
    "classNames": []
}
```

Then use `Bxsh(custom-shadow)` in your markup.

As a side note, you could also use a custom property (CSS variable); using "`var(--custom-shadow)`" as value and define the box-shadow you want in a stylesheet or in a `style` attribute. 

Or you could also create a custom rule in a stylesheet (not everything needs to come from Atomizer).

**Comment by redonkulus** [comment]
Closing this complex values are best suited by using custom values instead of trying to make the already complicated regex, more complicated.
