### ISSUE TITLE
Add option to minify the generated CSS

### ISSUE THREAD

**Issue by chinchang** [acss-io/atomizer#311]
There could be a flag on atomizer to minify the generated CSS.
If this makes sense, I can contribute on this.

**Comment by jitendravyas** [comment]
Last year @pankajparashar was thinking to sent a PR for this too https://gitter.im/acss-io/atomizer?at=581437a0c3569a036e2ebc79 

But I guess he hasn't sent yet. It would be surely useful.

But should it be as an option in atomic config file and atomizer alone should be able to do this or you are talking about adding this to Atomizer's plugin

https://github.com/acss-io/grunt-atomizer
https://github.com/acss-io/webpack-atomizer-loader
https://github.com/acss-io/gulp-atomizer

cc: @thierryk @src-code

**Comment by thierryk** [comment]
I think there are tools out there that are meant to do this job.

I believe @pankajparashar mentioned this as a mean to make Atomizer "self-sufficient": 

> One more thing about Atomizer that not many people talk about, is that it is a self-sufficient project.

but as far as I know, Atomizer does not add vendor prefixes, so we'd need more than adding minification to make it really "self-sufficient". 

In my opinion, I don't think that should be Atomizer responsibility as any given project should contain more than an Atomizer styles sheet, hence should require to run a tool on those non-ACSS rules to properly minify their CSS as a whole.

Yes, Atomizer could minify the rules it creates but I think it would just be "redundant" for most projects (projects in which devs already minify their assets).

**Comment by tom76kimo** [comment]
I agree with @thierryk , Atomizer should only focus on generating acss classes. Let other tools to do the pre or post process for it.

`webpack-atomizer-loader` has an option help to minimize CSS, or you can add `post-css` plugins you want to process generated css file.

https://github.com/acss-io/webpack-atomizer-loader/pull/14

**Comment by chinchang** [comment]
Makes sense. Closing this.
