### ISSUE TITLE
:link, :visited, :hover, and :active pseudo-classes should be ordered (in that sequence).

### ISSUE THREAD

**Issue by chhavi-khandelwal** [acss-io/atomizer#316]
```HTML

<button class="Bgc(#e6b105):h   Bgc(#000000):a  Bgc(#eeeff1)">12345678</button>

```

```Generated CSS
.Bgc\(\#000000\)\:a:active {
  background-color: #000000;
}
.Bgc\(\#e6b105\)\:h:hover {
  background-color: #e6b105;
}
.Bgc\(\#eeeff1\) {
  background-color: #eeeff1;
}
```
While clicking the button, active state triggers and hover state also applies. But in generated CSS active state CSS is overriden by hover state.
Correct order should be: 
```
link
visited
hover
active
```
Reference doc: https://css-tricks.com/almanac/selectors/a/active/

**Comment by thierryk** [comment]
@src-code @renatoi @redonkulus This is a good catch from @chhavi-khandelwal

**Comment by tomassentkeresty** [comment]
Hello, you can also consider putting :focus before :hover and :active.

**Comment by src-code** [comment]
Thanks everyone!  This will land in 3.5.0
