### ISSUE TITLE
How to add new atomic classes to atomic.css

### ISSUE THREAD

**Issue by jordiviva** [acss-io/atomizer#322]
Hello, I wanted to add to atomicss the funcionability of

#atomic .Jc\(se\) {
  justify-content: space-evenly;
}

I cant add it directly to atomic.css, since it's being deleted everytime my web is compiled, so I added it to a custom css file, but ofc atomicss is giving me a warning, so I tried to add it in custom, but then the web don't compile and have errors.

Warning: Class `Jc(se)` is ambiguous, and must be manually added to your config file:
"custom": {
    "Jc(se)": <YOUR-CUSTOM-VALUE>
}

Is there any way to generate new atomic classes inside atomic configuration? and how can I do it, if its possible.

**Comment by thinker3197** [comment]
In your atomic config, add `'se': 'space-evenly'`. Now you can use `Jc(se)` class as usual.

**Comment by jordiviva** [comment]
It works,  thanks for your fast response.
