### ISSUE TITLE
::pl doesn't work, ::placeholder does

### ISSUE THREAD

**Issue by rzfang** [acss-io/atomizer#329]
As title mentioned, I think the document gives the wrong guide.
https://acss.io/guides/syntax.html

I use 3.4.8, by the way.

**Comment by tom76kimo** [comment]
hmm...it looks should be `::ph` I think
https://github.com/acss-io/atomizer/blob/master/src/lib/grammar.js#L47

**Comment by src-code** [comment]
Thanks @rzfang and @tom76kimo, the docs site has been updated!
