### ISSUE TITLE
Question - Alpha transparency

### ISSUE THREAD

**Issue by sarbbottam** [acss-io/atomizer#340]
```
// acss.config.js
module.exports = {
  'custom' : {
     black: '#000',
     black015: '#000.15'
  }
}
```

```
// .html
class="Bdbc(#000.15) Bdbc(black015) Bdbc(black)"
``` 

```
// generated css file
.Bdbc\(\#000\.15\) {
  border-bottom-color: rgba(0,0,0,.15);
}
.Bdbc\(black015\) {
  border-bottom-color: #000.15;
}
.Bdbc\(black\) {
  border-bottom-color: black;
}
```

Hi @renatoi, @src-code, @thierryk, 

Happy Holidays!

With respect to the above example I am trying to avoid any random values in the html and rely on the `custom` hash of the config file. Unfortunately I am unable to do it correctly.
I am wondering if there is a better way tp generate rules with alpha transparency from predefined custom properties.

Any pointer would be helpful.

Thank you!

**Comment by sarbbottam** [comment]
That works for me! Thanks!

Please feel free to close the issue if supporting something like `#000.15` is not in scope.

**Comment by src-code** [comment]
Custom values aren't interpreted currently, I'm not sure it'd be worth it to go down that path.  I'd stick with what @tom76kimo suggested above.
