### ISSUE TITLE
Support for CSS variables (CSS custom properties)

### ISSUE THREAD

**Issue by chinchang** [acss-io/atomizer#351]
I was trying to use this class: `Bgc(var(--clr-bg))`
And atomizer didn’t compile it.

**Expected output**:

```
.Bgc\(var\(--clr-bg\)\) {
 background-color: var(--clr-bg);
}
```

**Actual Output**:

`Nothing compiles`

CC @roderickhsiao  @src-code @renatoi

**Comment by roderickhsiao** [comment]
I think this might worth to revisit 

Currently we can add a custom variable in the config like

```
clr-bg: var(--clr-bg)
```

And in Atomic we use as custom variable `Bgc(clr-bg)`.

However, we will need to manually create a CSS file for the variable somewhere.

```css
--clr-bg: #fff; 
```

**Comment by thierryk** [comment]
What about going this route:

class:

```
Bgc(--clr-bg)
```

output:

```
.Bgc\(--clr-bg\) {
    background-color: var(--clr-bg);
}
```

As a side note, the variable _does not need_ to live in a CSS file, it could be declared on any node via a `style` attribute (`style="--clr-bg: teal;"`)  or inside a `<style>` block:

```
<style>
:root {
    --clr-bg: teal;
}
</style>
```

That way authors can use variables without having to edit the config nor create a stylesheet. 

Note that with custom properties **scope** is an issue, so people would need to know what they are doing.

**Comment by idmytro** [comment]
I thought about this option
`Bgc$(clr-bg)` --> `background-color: var(--clr-bg)`
but this is not optimal for multiple arguments, where for example 1 is a variable, but 2 is not.

**Comment by idmytro** [comment]
Windicss has this feature and use `$` sign

https://windicss.org/guide/features.html#variables

**Comment by thierryk** [comment]
FWIW, I think I prefer `Bgc(--clr-bg)` over `Bgc$(clr-bg)`.
I believe the former facilitates mixing custom properties and standard values (between the parenthesis), for example:

```
Skew(20deg,--customAngle)
```

**Comment by redonkulus** [comment]
@chinchang @thierryk fixed by https://github.com/acss-io/atomizer/pull/395
