### ISSUE TITLE
How to integrate atomizer in an Angular project?

### ISSUE THREAD

**Issue by fidian** [acss-io/atomizer#352]
Angular has a [build system](https://cli.angular.io/) that sets up a project, performs builds, and does many other tasks. The build system uses webpack under the hood and there's some support for [custom builders](https://www.npmjs.com/package/@angular-builders/custom-webpack) with Angular 8, though I am at a complete loss for how to get [webpack-atomizer-loader](https://github.com/acss-io/webpack-atomizer-loader) to work with the project.

Is there a sample, "Hello world!" type of repository that illustrates how to use Atomizer within an Angular project? I've tried for a couple days to get an approach to work. After many failures, I've fallen back on writing a script so the dev server will run in the foreground while Atomizer will run behind the scenes.

```
#!/usr/bin/env bash
# Change to the directory of the script
cd "${0%/*}" || :

(
    while true; do
        # Sometimes this crashes, so wait 1 second and restart
        atomizer -c atomizer.js -o src/atomic.css -r atomizer-rules.js -w 'src/**/*.{html,ts}'
        sleep 1
    done
) &
backgroundPid=$!
trap "kill $backgroundPid > /dev/null 2>&1" EXIT

ng serve
```

Does anyone have a better approach?

Tip for others following this approach: Angular components can assign dynamic classes using `HostBinding('class.H(100%)')`. If you want Atomizer to pick up on the classes, use string concatenation to separate the "class." portion: `HostBinding('class.' + 'H(100%)')`.

**Comment by tom76kimo** [comment]
Not familiar with Angular, could you please share your webpack setting?

**Comment by fidian** [comment]
That's one of the rubs of using Angular's build system. They intentionally
hide Webpack and its configuration. It's not something I can control.

--
Tyler Akins

**Comment by tom76kimo** [comment]
Oh...that's difficult to integrate `webpack-atomizer-loader` with no place to configure.

**Comment by fidian** [comment]
Was there a way to integrate this with Angular?

**Comment by b-mi** [comment]
> Was there a way to integrate this with Angular?

It seems it is not possible. Your question was not answered and the question was closed.

I spent a few hours about how to use in angular - without result.
