### ISSUE TITLE
Jc(se): space-evenly not supported

### ISSUE THREAD

**Issue by fidian** [acss-io/atomizer#353]
`Jc(sb)` works as expected, as does `Jc(sa)`, but `Jc(se)` does not exist. It's [widely supported](https://caniuse.com/#feat=justify-content-space-evenly). The CSS 3 spec says it's a member of [`content-distribution`](https://www.w3.org/TR/css-align-3/#typedef-content-distribution), which [applies to `justify-content`](https://www.w3.org/TR/css-align-3/#propdef-justify-content) according to W3C Working Draft, 6 December 2018. Can this get added to atomizer so I don't need to add a custom value as was done in #322?

**Comment by src-code** [comment]
Added in v3.6.1

**Comment by fidian** [comment]
Thanks! It works like a charm.
