### ISSUE TITLE
custom-param should allow commas

### ISSUE THREAD

**Issue by nsaunders** [acss-io/atomizer#362]
Consider, for example, the `Tsh` function:

```
Tsh(<custom-param>)
text-shadow: value
```

I would like to parameterize my custom values by size and color, e. g. `Tsh(sm,gray300)`, by adding something like the following to my config:

```
{
  custom: {
    "Tsh(sm,gray300)": "1px 1px #ccc"
  }
}
```

This is currently not possible because the `parseConfig` function does not check for `config.custom.hasOwnProperty("Tsh(sm,gray300)")` before splitting `sm,gray300` and treating `sm` and `gray300` as separate values.

**Comment by src-code** [comment]
I think this is too ambiguous and could lead to confusion - commas are reserved syntax in Atomizer for classes that support multiple values.  And `text-shadow` itself, as an example, uses commas to support multiple text-shadow definitions (eg `text-shadow: 1px 1px black, 2px 2px white;`), so this could lead to confusion as to how that comma is being interpreted for a given rule.  I think it would be better to use a different separator in your example that's less ambiguous, eg a dash or underscore.

**Comment by nsaunders** [comment]
I do see your point; but, at the same time, I think one would expect an explicit, highly specific key specified in `custom` configuration to override default behavior, reserved syntax or otherwise. I think of it somewhat like Pattern Matching, I suppose.

Alternatively, it would be great to be able to specify a custom rule that overrides a default rule by having the same "matcher". [This appears not to be possible currently.](https://github.com/acss-io/atomizer/blob/master/src/atomizer.js#L41)

By the way, does `Tsh` have a bug? Consider the test I just did:

config.js:
```
module.exports = {
  custom: {
    foo: "1px 1px 0 #666",
    bar: "-1px -1px 0 #006",
  },
};
```

index.html:
```
<h1 class="Tsh(foo,bar)">Hi</h1>
```

atomizer:
```
atomizer -c config.js index.html
```

Output:
```
.Tsh\(foo\,bar\) {
  text-shadow: 1px 1px 0 #666;
}
```

**Comment by nsaunders** [comment]
I’ll go ahead and close so as not to clutter the issues page. The real solution may be to address #366, although it’s a totally subjective issue without necessarily a right answer.
