### ISSUE TITLE
Is it possible to change the class name?

### ISSUE THREAD

**Issue by jiameng123** [acss-io/atomizer#372]
Is it possible to change the class name? For example: Px (2px) is replaced by Px [2px], and the class name Px \ (2px \) in the generated CSS file is replaced by .Px [2px]; can this effect be achieved? What should I do, I look forward to replying. thank you very much

**Comment by jitendravyas** [comment]
Can I know Why do you want to do this?

**Comment by jiameng123** [comment]
> Can I know Why do you want to do this?

I am developing a small program with an embedded name called We chat APP. It may be unique to China and very popular in China. Its style files are suffixed with .wxs, similar to css, but do not support "\" escape Characters are class names
