### ISSUE TITLE
RFC: New syntax for custom value string replacement

### ISSUE THREAD

**Issue by src-code** [acss-io/atomizer#377]
It's been requested to offer an easy way in Atomizer's custom value syntax to do simple string replacement of other custom values.  This could be especially useful in cases where multiple atomizer configs are being combined from different sources, such as when defining a global color palette as part of a design language, and you want to reference that single source of truth in other custom values.

For example, one could have the following global color custom value config:

```json
{
  "custom": {
    "main-color": "#ff12cd",
    "secondary-color": "#0982ac"
  }
}
```

You may want to use those same color values in another atomizer config to define a gradient:

```json
{
  "custom": {
    "my-gradient" : "linear-gradient(to bottom, #ff12cd, #0982ac)"
  }
}
```

It's been proposed to offer a new syntax that is unique to Atomizer and will not be confused with other custom value naming conventions that may already be in use elsewhere (e.g. key names with prefixes like `$`, etc.) or CSS variable syntax. 

Proposed solution is to introduce a `acss()` syntax for use inside custom values:

```json
{
  "custom": {
    "my-gradient" : "linear-gradient(to bottom, acss(main-color), acss(secondary-color))"
  }
}
``` 

This `acss()` syntax would give Atomizer a clear signal that the token needs to be replaced with another custom value, which could also be further dereferenced if found to contain other substitution tokens, and so on.  This syntax would be backwards compatible as it should not collide with existing configs in the wild, and would not be exposed in output CSS (if a custom value is found not to exist, it would be replaced with empty string.)  

I'm open to suggestions though on the exact name of this syntax if people don't like `acss()`.  

cc @renatoi @thierryk @redonkulus

**Comment by thierryk** [comment]
2 questions:

  * what about using something that may "speak" to everyone: `!{main-color}` ?
  * what about offering the option to include a default value: `!{main-color, #fff}`

PS: @renatoi, @redonkulus, @src-code I hope all is well on your end - stay safe!

**Comment by redonkulus** [comment]
I'm open to any syntax really, the `!` is pretty well known in CSS today, not sure if that syntax would confuse people. The `acss()` or `acss{}` (to make it look less function like) it a little clearer on the intent IMO.

**Comment by thierryk** [comment]
I've updated my comment above as I had `!` instead of `#` in there (duh!).
The idea is to have something similar to Sass (Pug or else) when it comes to interpolation as many people may already be familiar with that syntax.

I'd vote for `{}` versus `()` as the former seems widely used for this (i.e. `#{...}`, `{{...}}`, `${...}`).

I'm not sure I like the idea of using `acss` in there though as it does not really convey "embedding" something and definitely looks like a function if used with `()`.

**Comment by redonkulus** [comment]
Ok, I like the `#{}` syntax better than `!`. The fallback idea is interesting too, although I'd rather just have atomizer spit out a warning that it could not find the value to replace. Since its not dynamic, the dev should know about the error at build time.

**Comment by renatoi** [comment]
I like this idea and I do like the idea of using `#{}`. I guess `#{}` is better than `${}` so that it's not confused with the js template literal, correct?

> Since its not dynamic, the dev should know about the error at build time.

+1 on this

**Comment by carriemorrison** [comment]
```
{
  "custom": {
    "my-gradient" : "linear-gradient(to bottom, #{main-color}, #{secondary-color})"
  }
}
```
I like it, also Hi everyone hope your all staying safe and sane 👯‍♀️

**Comment by snyamathi** [comment]
I like it - agree with @redonkulus that a fallback, while a nice-to-have, is not really necessary and the warning is fine and less confusing.

**Comment by src-code** [comment]
https://github.com/acss-io/atomizer/releases/tag/%403.8.0
