### ISSUE TITLE
Are there any plugin or plans to add attribute mode?

### ISSUE THREAD

**Issue by rssilvaba** [acss-io/atomizer#397]
Hi all,

I have been using ACSS a lot lately specially for how easy and straight forward it is to get started compared to the mainstream utility CSS frameworks.

One thing that I think is useful is the attribute mode that many of them are starting to support. 
And the great thing about is that you get truly composable utility classes as in react it will always keep the last attribute you entered. Which does not happen via classnames.

Are there any plugin or plans to add attribute mode?

Or if anyone wants to give a hand any short js that can transform the classname string into a js map that I can use to keep the values that where last entered.

Ex: "Pos(r) Fz(14px) Ff(--ff-primary) Ai(c) D(if)" would become: {Pos: 'r' , Fz: '14px',  Ff: '--ff-primary', Ai:'c', D: 'if'}
Here is what I came up:
"Pos(r) Fz(14px) Ff(--ff-primary) Ai(c) D(if)".split(' ').reduce((acc,cv)=>({[cv.split('(')[0]]:cv.split('(')[1].replace(')',''), ...acc}),{})

PS: this might be probably there in the code already, any ways I can import into a js module?

**Comment by redonkulus** [comment]
We do not publish anything currently, but you could certainly create a utility and publish to npm for others to use.
