### ISSUE TITLE
Atomizer plugin not working on a vite project

### ISSUE THREAD

**Issue by maheshbansod** [acss-io/atomizer#550]
**Describe the bug** A clear and concise description of what the bug is.
I've followed the instructions here: https://acss.io/integrations/vite.html.  
but the classes I add in my `index.html` file aren't getting generated.   
The file `atomizer.css` is not generated.   
I've created the repo https://github.com/maheshbansod/atomizer-vite which shows this.  
I'm having the same problem on vite+ts project too.

**To Reproduce** Steps to reproduce the behavior:

1. Follow instructions at https://acss.io/integrations/vite.html
2. Add any atomizer class
3. Check dist folder

**Expected behavior** A clear and concise description of what you expected to happen.
The file `dist/atomizer.css` should be generated with correct classes.

**Additional context** Add any other context about the problem here.

-   OS: [e.g. iOS8.1]
-   Package atomizer-plugins
-   Version ^1.2.0

**Comment by redonkulus** [comment]
@maheshbansod thanks for the report. I found the same issues as you locally when testing and [committed a fix](https://github.com/acss-io/atomizer/commit/1ab3c382c1e4dc803e06e382276791bb78e03a4a) to help. 

Note that building atomizer still requires a manual step as vite does not automatically re-run atomizer on file changes. I'm not sure why that is, I will have to dig into the vite docs to see if that is something that can be enabled or something our plugin will have to do.

**Comment by maheshbansod** [comment]
thanks for the response @redonkulus.
As for me, I couldn't find any config that could enable/disable this.
I wrote a Vite plugin inspired by unplugin atomizer in `atomizer-plugins` to enable re-running atomizer on change.
Not sure about the performance impact, I simply decided to write to the `outfile` on every transform. Debounce on that might help with the performance a bit.

**Comment by redonkulus** [comment]
Interesting idea, can you send me the code, I can test it out and see about including it in the plugin library.

**Comment by maheshbansod** [comment]
Added the code here: https://github.com/maheshbansod/atomizer-vite/blob/main/atomizerPlugin.ts

**Comment by maheshbansod** [comment]
awesome. thanks.
