### ISSUE TITLE
Can we have a support of "inset" CSS Property in AtomicCSS?

### ISSUE THREAD

**Issue by aakashgill** [acss-io/atomizer#635]
[inset CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/inset)

Instead of writing all these classes `T(0) Start(0) End(0) B(0)`,
I'd prefer to simply write something like In(0) or I(0), whatever works.

Its [browser compatibility](https://caniuse.com/?search=inset) is also good, I guess.
Really looking forward to it.

Thanks

**Comment by redonkulus** [comment]
@aakashgill I think that would be fine to add, it could be added as a helper, https://github.com/acss-io/atomizer/blob/main/packages/atomizer/src/helpers.js

I think using `In()` would make sense too. Want to open a PR to add it?

**Comment by redonkulus** [comment]
https://github.com/acss-io/atomizer/pull/645
