### ISSUE TITLE
Update the atomizer version to the latest version

### ISSUE THREAD

**Issue by Akhileshrcr** [acss-io/atomizer#855]
Current atomizer version is 4.0.0 and which supports all latest CSS properties but in our current grunt atomizer it seems like have an older version of atomizer (3.0.0).
We don't have access to the latest CSS properties in grunt atomizer because it contains older version of atomizer.

**Comment by redonkulus** [comment]
There is no atomizer v4 today, 3.28.0 is the latest version. Where are you seeing v4?
