### ISSUE TITLE
https://acss.io returns a 404 error message

### ISSUE THREAD

**Issue by tinder-kyleboss** [acss-io/atomizer#910]
**Describe the bug** A clear and concise description of what the bug is.
Resource page acss.io is down.

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://acss.io
2. Observe Github Pages 404 error.

**Expected behavior** A clear and concise description of what you expected to happen.
https://acss.io renders.

**Additional context** Add any other context about the problem here.
Apologies for the abnormal issue - nothing is wrong with atomizer, but wanted to bubble up the issue with the acss.io page as it was a helpful resource for many who are using or onboarding onto the library.

**Comment by jitendravyas** [comment]
Please use this url https://acss-io.github.io/atomizer/

**Comment by redonkulus** [comment]
Thanks @jitendravyas, we are deprecating the acss.io domain in favor of the GitHub page URL. We are in the process of updating the acss.io domain to redirect to the new URL.

**Comment by 6zz** [comment]
All the sub pages under integrations are still 404s: https://acss-io.github.io/atomizer/installation.html#integrations

**Comment by redonkulus** [comment]
@6zz thank you for finding this. I forgot to update those links, its fixed now. acss.io is also redirecting to GitHub Pages now so that should be resolved.
